version: '3'

services:
  blog-server:
    build: ./docker/php
    image: blog-symfony
    depends_on:
      - db
    volumes:
      - ./:/application:cached
      - /application/var/sessions/

  db:
    image: mysql:5.7
    ports:
      - '3308:3308'
    environment:
      MYSQL_DATABASE: symfony-blog
      MYSQL_PASSWORD: secret_test
      MYSQL_TCP_PORT: 3308
    volumes:
      - ./tmp/db:/var/lib/mysql

  dbtest:
    image: mysql:5.7
    ports:
      - '3309:3309'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony-blog-test
      MYSQL_USER: gandalf
      MYSQL_PASSWORD: secret_test
      MYSQL_TCP_PORT: 3309
    volumes:
      - ./tmp/test:/var/lib/mysql

  nginx:
    image: nginx
    ports:
      - '8009:80'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application:cached
      - ./var/log/nginx:/var/log/nginx
    depends_on:
      - blog-server

  mercure:
    image: dunglas/mercure
    ports:
      - '3005:80'
    environment:
      - JWT_KEY=symfonyBlogJwtToken
      - PUBLISH_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_ORIGINS=http://symfony-blog.fr:8000
      - DEBUG=1
